import 'package:fast_app_base/screen/main/tab/stock/vo_stock.dart';

import '../../../../../common/constants.dart';

List<Stock> popularStockList = [
  Stock(yesterdayColsePrice: 41600,
    currentPrice: 41600,
    stockName: "한화솔루션",
    stockImagePath: "$basePath/stock/interest_stock_01.png",),
  Stock(yesterdayColsePrice: 217000,
    currentPrice: 219000,
    stockName: "현대모비스",
    stockImagePath: "$basePath/stock/interest_stock_02.png",),
  Stock(yesterdayColsePrice: 80000,
    currentPrice: 78000,
    stockName: "셀트리온",
    stockImagePath: "$basePath/stock/interest_stock_03.png",),
  Stock(yesterdayColsePrice: 80000,
    currentPrice: 92300,
    stockName: "하이브",
    stockImagePath: "$basePath/stock/interest_stock_04.png",),
  Stock(yesterdayColsePrice: 100030,
    currentPrice: 132000,
    stockName: "LG 전자",
    stockImagePath: "$basePath/stock/interest_stock_05.png",),
  Stock(yesterdayColsePrice: 121000,
    currentPrice: 130900,
    stockName: "Tihan",
    stockImagePath: "$basePath/stock/interest_stock_06.png",),
  Stock(yesterdayColsePrice: 151000,
    currentPrice: 153000,
    stockName: "SK 하이닉스",
    stockImagePath: "$basePath/stock/interest_stock_07.png",),
  Stock(yesterdayColsePrice: 211000,
    currentPrice: 211900,
    stockName: "삼성",
    stockImagePath: "$basePath/stock/interest_stock_08.png",),
  Stock(yesterdayColsePrice: 89000,
    currentPrice: 90000,
    stockName: "카카오",
    stockImagePath: "$basePath/stock/interest_stock_09.png",),
  Stock(yesterdayColsePrice: 66000,
    currentPrice: 59610,
    stockName: "LG 생활과학",
    stockImagePath: "$basePath/stock/interest_stock_10.png",),
];